# https://aka.ms/yaml

trigger:
 branches:
   include:
    - master
    - features/*
    - feature/*
    - releases/*
    - dev/*
 paths:
    include:
      - src/*

variables:
  - group: GitRelease

  - name: patch
    value: $[counter('versioncounter', 100)]
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: GitHubApplicationName
    value: 'Amusoft.VisualStudio.TemplateGenerator'
  - name: GitHubRepoName
    value: 'Amusoft.VisualStudio.TemplateGenerator'
  - name: GitHubAssetsPattern
    value: '$(Build.ArtifactStagingDirectory)\*.zip'
  - name: GitHubAccessToken
    value: '$(gitAccessToken)'
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - name: BUILD_PUBLISH_ARTIFACTS
    value: $[or(startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))]
  - name: BUILD_IS_RELEASE
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')]
  - name: BUILD_IS_ALPHA
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

pool:
  vmImage: 'windows-2019'

jobs:

- job:
  displayName: Build
  condition: succeeded()
  steps:

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      verbosityRestore: 'Minimal'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: dotnet pack release
    condition: and(succeeded(), eq(variables['BUILD_IS_RELEASE'], 'True'))
    inputs:
      command: 'pack'
      packagesToPack: '**/*CommandLine.csproj'
      configuration: '$(buildConfiguration)'
      packDirectory: '$(Build.ArtifactStagingDirectory)\nupkg'
      includesymbols: true
      versioningScheme: 'off'
      buildProperties: 'PackAsTool=True;SymbolPackageFormat=snupkg'
      verbosityPack: 'Minimal'

  - task: DotNetCoreCLI@2
    displayName: dotnet pack alpha
    condition: and(succeeded(), eq(variables['BUILD_IS_ALPHA'], 'True'))
    inputs:
      command: 'pack'
      packagesToPack: '**/*CommandLine.csproj'
      configuration: '$(buildConfiguration)'
      packDirectory: '$(Build.ArtifactStagingDirectory)\nupkg'
      includesymbols: true
      versioningScheme: 'off'
      buildProperties: 'PackAsTool=True;SymbolPackageFormat=snupkg;VersionSuffix=alpha$(Build.BuildId)'
      verbosityPack: 'Minimal'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'], 'True'))
    displayName: dotnet publish
    inputs:
      targetType: 'inline'
      script: |
        mkdir $(Build.ArtifactStagingDirectory)\desktop
        & dotnet build $(Build.SourcesDirectory)\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj -r win-x64 -c $(buildConfiguration)
        & dotnet publish $(Build.SourcesDirectory)\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj -r win-x64 -c $(buildConfiguration) --self-contained --no-build -o $(Build.ArtifactStagingDirectory)\desktop
        
        mkdir $(Build.ArtifactStagingDirectory)\cli-netcore2.1-standalone
        mkdir $(Build.ArtifactStagingDirectory)\cli-netcore2.1-shared
        & dotnet publish $(Build.SourcesDirectory)\src\Generator.Client.CommandLine\Generator.Client.CommandLine.csproj -r win-x64 -f netcoreapp2.1 -c $(buildConfiguration) --self-contained true -o $(Build.ArtifactStagingDirectory)\cli-netcore2.1-standalone
        & dotnet publish $(Build.SourcesDirectory)\src\Generator.Client.CommandLine\Generator.Client.CommandLine.csproj -r win-x64 -f netcoreapp2.1 -c $(buildConfiguration) --self-contained false -o $(Build.ArtifactStagingDirectory)\cli-netcore2.1-shared

  - task: CopyFiles@2
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'],'True'))
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **/*.md
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'],'True'))
    displayName: zip artifacts
    inputs:
      targetType: 'inline'
      script: |
        7z a $(Build.ArtifactStagingDirectory)\TemplateGenerator_$(Build.BuildId)_win64.zip $(Build.ArtifactStagingDirectory)\*

  - task: PublishPipelineArtifact@0
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'],'True'))
    inputs:
      artifactName: 'drop'
      targetPath: '$(Build.ArtifactStagingDirectory)\TemplateGenerator_$(Build.BuildId)_win64.zip'

  - task: PublishPipelineArtifact@0
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'],'True'))
    inputs:
      artifactName: 'nupkg'
      targetPath: '$(Build.ArtifactStagingDirectory)\nupkg'