# https://aka.ms/yaml

trigger:
 branches:
   include:
    - master
    - features/*
    - feature/*
    - releases/*
 paths:
    include:
      - src/*

variables:
  - group: GitRelease

  - name: patch
    value: $[counter('versioncounter', 100)]
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: GitHubApplicationName
    value: 'Amusoft.VisualStudio.TemplateGenerator'
  - name: GitHubRepoName
    value: 'Amusoft.VisualStudio.TemplateGenerator'
  - name: GitHubAssetsPattern
    value: '$(Build.ArtifactStagingDirectory)\*.zip'
  - name: GitHubAccessToken
    value: '$(gitAccessToken)'
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - name: BUILD_PUBLISH_ARTIFACTS
    value: $[or(startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))]
  - name: BUILD_IS_RELEASE
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')]
  - name: BUILD_IS_ALPHA
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

pool:
  vmImage: 'ubuntu-latest'
  #vmImage: 'windows-2019'

jobs:

- job:
  displayName: Build
  condition: succeeded()
  steps:

  - task: PowerShell@2  
    displayName: GetVersion .Desktop
    inputs:
      filePath: 'build\csproj-version-to-pipeline.ps1'
      arguments: '$(patch) $(Build.SourcesDirectory)\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj PackageVersion'

  - task: PowerShell@2  
    displayName: GetVersion .CLI
    inputs:
      filePath: 'build\csproj-version-to-pipeline.ps1'
      arguments: '$(patch) $(Build.SourcesDirectory)\src\Generator.Client.CommandLine\Generator.Client.CommandLine.csproj PackageVersionCLI'

  - task: NuGetToolInstaller@1
    enabled: false
    inputs:
      versionSpec: '4.x'

  - task: NuGetCommand@2
    enabled: false
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: VSBuild@1
    enabled: false
    inputs:
      solution: '**\*.sln'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    enabled: false
    condition: succeeded()
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      verbosityRestore: 'Minimal'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: 'pack'
      packagesToPack: '**/*CommandLine.csproj'
      configuration: '$(buildConfiguration)'
      packDirectory: '$(Build.ArtifactStagingDirectory)\nupkg'
      includesymbols: true
      versioningScheme: 'off'
      buildProperties: 'PackAsTool=True;VersionPrefix=9.8.7.6;SymbolPackageFormat=snupkg;VersionSuffix=alpha'
      verbosityPack: 'Minimal'
#$(buildConfiguration) -o  p:VersionPrefix=$(PackageVersionCLI) "

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'], 'True'))
    displayName: dotnet publish
    inputs:
      targetType: 'inline'
      script: |
        mkdir $(Build.ArtifactStagingDirectory)\desktop
        & dotnet build $(Build.SourcesDirectory)\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj -r win-x64 -c $(buildConfiguration)
        & dotnet publish $(Build.SourcesDirectory)\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj -r win-x64 -c $(buildConfiguration) --self-contained --no-build -o $(Build.ArtifactStagingDirectory)\desktop
        
        mkdir $(Build.ArtifactStagingDirectory)\cli-netcore2.1-standalone
        mkdir $(Build.ArtifactStagingDirectory)\cli-netcore2.1-shared
        & dotnet publish $(Build.SourcesDirectory)\src\Generator.Client.CommandLine\Generator.Client.CommandLine.csproj -r win-x64 -f netcoreapp2.1 -c $(buildConfiguration) --self-contained true -o $(Build.ArtifactStagingDirectory)\cli-netcore2.1-standalone
        & dotnet publish $(Build.SourcesDirectory)\src\Generator.Client.CommandLine\Generator.Client.CommandLine.csproj -r win-x64 -f netcoreapp2.1 -c $(buildConfiguration) --self-contained false -o $(Build.ArtifactStagingDirectory)\cli-netcore2.1-shared

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['BUILD_IS_RELEASE'], 'True'))
    displayName: dotnet pack release
    inputs:
      targetType: 'inline'
      script: |
        mkdir $(Build.ArtifactStagingDirectory)\nupkg
        Write-Host $(PackageVersion)
        Write-Host $(PackageVersionCLI)
        & dotnet pack $(Build.SourcesDirectory)\src\Generator.Client.CommandLine\Generator.Client.CommandLine.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)\nupkg /p:PackAsTool=true /p:VersionPrefix=$(PackageVersionCLI) /p:SymbolPackageFormat=snupkg /p:IncludeSymbols=True --version-suffix=beta

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['BUILD_IS_ALPHA'], 'True'))
    displayName: dotnet pack alpha
    inputs:
      targetType: 'inline'
      script: |
        dotnet --version
        mkdir $(Build.ArtifactStagingDirectory)\nupkg
        Write-Host $(PackageVersionCLI)
        $commandSample = "dotnet pack $(Build.SourcesDirectory)\src\Generator.Client.CommandLine\Generator.Client.CommandLine.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)\nupkg /p:PackAsTool=true /p:VersionPrefix=$(PackageVersionCLI) /p:SymbolPackageFormat=snupkg /p:IncludeSymbols=True /p:VersionSuffix=alpha"
        Write-Host $commandSample
        Invoke-Expression $commandSample

        & dotnet pack $(Build.SourcesDirectory)\src\Generator.Client.CommandLine\Generator.Client.CommandLine.csproj -c $(buildConfiguration) -o $(Agent.TempDirectory)\nupkg /p:PackAsTool=true /p:VersionPrefix=9.8.7 /p:SymbolPackageFormat=snupkg /p:IncludeSymbols=True /p:VersionSuffix=alpha

  - task: CopyFiles@2
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'],'True'))
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **/*.md
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'],'True'))
    displayName: zip artifacts
    inputs:
      targetType: 'inline'
      script: |
        7z a $(Build.ArtifactStagingDirectory)\TemplateGenerator_$(PackageVersion)_win64.zip $(Build.ArtifactStagingDirectory)\*

  - task: PublishPipelineArtifact@0
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'],'True'))
    inputs:
      artifactName: 'drop'
      targetPath: '$(Build.ArtifactStagingDirectory)\TemplateGenerator_$(PackageVersion)_win64.zip'

  - task: PublishPipelineArtifact@0
    condition: and(succeeded(), eq(variables['BUILD_PUBLISH_ARTIFACTS'],'True'))
    inputs:
      artifactName: 'nupkg'
      targetPath: '$(Build.ArtifactStagingDirectory)\nupkg'
