# https://aka.ms/yaml

trigger:
 branches:
   include:
     - master
     - features/*
     - feature/*
     - releases/*
 paths:
   exclude:
     - README.md
     - azure-pipelines.yml

variables:
  patch: $[counter('versioncounter', 100)]
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  GitHubApplicationName: 'Amusoft.VisualStudio.TemplateGenerator'
  GitHubRepoName: 'Amusoft.VisualStudio.TemplateGenerator'
  GitHubAssetsPattern : '$(Build.ArtifactStagingDirectory)\*.zip'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

pool:
  vmImage: 'windows-2019'

jobs:
- job:
  displayName: Build
  condition: succeeded()
  steps:

  - task: PowerShell@2
    displayName: Get Projectversion from file
    inputs:
      filePath: 'build\csproj-version-to-pipeline.ps1'
      arguments: '$(patch) $(Build.SourcesDirectory)\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj PackageVersion'
    
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        
        & dotnet restore $(Build.SourcesDirectory)\src\Generator.sln
        & dotnet build $(Build.SourcesDirectory)\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj -r win-x64 -c Release
        & dotnet test $(Build.SourcesDirectory)\src\Generator.sln
        
  - task: VSTest@2
    enabled: false
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        
        & dotnet publish $(Build.SourcesDirectory)\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj -v n -r win-x64 -c Release --self-contained --no-build -o $(Build.ArtifactStagingDirectory) /p:PublishSingleFile=true /p:PublishTrimmed=true
        & dir $(Build.ArtifactStagingDirectory)\
        & 7z a $(Build.ArtifactStagingDirectory)\Release.zip $(Build.ArtifactStagingDirectory)\*

  - task: CopyFiles@2
    enabled: true
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        README.md
        src/Generator.Client.Desktop/Release/**/*.exe
      TargetFolder: '$(Build.ArtifactStagingDirectory)'


  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'drop'
      targetPath: '$(Build.ArtifactStagingDirectory)'

  - task: PublishGitHubRelease@0
    enabled: false
    displayName: 'Publish-GitHub-Alpha'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
    inputs:
      applicationName: '$(GitHubApplicationName)'
      gitSourceOption: 'github'
      token: '$($gitAccessToken)'
      repo: '$(GitHubRepoName)'
      owner: 'taori'
      tagName: 'alpha-$(PackageVersion)'
      releaseName: 'alpha-$(PackageVersion)'
      releaseBody: 'automated release from Azure DevOps'
      draft: false
      prerelease: true
      assetsPattern: '$(GitHubAssetsPattern)'

  - task: PublishGitHubRelease@0
    enabled: false
    displayName: 'Publish-GitHub-Release'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')) 
    inputs:
      applicationName: '$(GitHubApplicationName)'
      gitSourceOption: 'github'
      token: '$($gitAccessToken)'
      repo: '$(GitHubRepoName)'
      owner: 'taori'
      tagName: 'release-$(PackageVersion)'
      releaseName: 'release-$(PackageVersion)'
      releaseBody: 'automated release from Azure DevOps'
      draft: false
      prerelease: false
      assetsPattern: '$(GitHubAssetsPattern)'
