name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: dotnet restore Generator.sln
      run: dotnet restore src/Generator.sln
    - name: dotnet build Generator.sln
      run: dotnet build src/Generator.sln -v d --configuration Release
